openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://127.0.0.1:51660/api/v1
    description: Generated server url
paths:
  /products/{id}:
    get:
      tags:
        - Products
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - Products
      operationId: update
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
        required: true
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
    delete:
      tags:
        - Products
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
  /orders/{orderId}/status:
    put:
      tags:
        - Orders
      operationId: updateStatus
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdateStatusRequest'
        required: true
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /products:
    get:
      tags:
        - Products
      operationId: list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
    post:
      tags:
        - Products
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /orders:
    get:
      tags:
        - Orders
      operationId: findOrders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
    post:
      tags:
        - Orders
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /orders/{orderId}/checkout:
    post:
      tags:
        - Orders
      operationId: checkout
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /customers:
    post:
      tags:
        - Customers
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /products/category/{categoryId}:
    get:
      tags:
        - Products
      operationId: findByCategory
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'
  /orders/{orderId}:
    get:
      tags:
        - Orders
      operationId: findById_1
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /orders/{orderId}/payment-update:
    get:
      tags:
        - Orders
      operationId: paymentUpdate
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /orders/payment-status/{orderId}:
    get:
      tags:
        - Orders
      operationId: checkPaymentStatus
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
  /health:
    get:
      tags:
        - health-controller
      operationId: ping
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /customers/search:
    get:
      tags:
        - Customers
      operationId: search
      parameters:
        - name: cpf
          in: query
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponses'
components:
  schemas:
    ProductRequest:
      required:
        - description
        - image
        - name
      type: object
      properties:
        name:
          type: string
        category:
          type: string
          enum:
            - LANCHE
            - ACOMPANHAMENTO
            - BEBIDA
            - SOBREMESA
        price:
          type: number
        description:
          type: string
        image:
          type: string
    OrderUpdateStatusRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - CREATED
            - AWAITING_PAYMENT
            - PAID
            - CANCELED
            - IN_PREPARATION
            - READY
            - AWAITING_WITHDRAWAL
            - COMPLETED
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ErrorResponses:
      type: object
      properties:
        errors:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ErrorResponse'
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
          enum:
            - LANCHE
            - ACOMPANHAMENTO
            - BEBIDA
            - SOBREMESA
        price:
          type: number
        description:
          type: string
        image:
          type: string
    OrderItemRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        observation:
          type: string
    OrderRequest:
      type: object
      properties:
        customerId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemRequest'
    OrderItemResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
          enum:
            - LANCHE
            - ACOMPANHAMENTO
            - BEBIDA
            - SOBREMESA
        price:
          type: number
        quantity:
          type: integer
          format: int32
        observation:
          type: string
    OrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: string
        amount:
          type: number
        status:
          type: string
          enum:
            - CREATED
            - AWAITING_PAYMENT
            - PAID
            - CANCELED
            - IN_PREPARATION
            - READY
            - AWAITING_WITHDRAWAL
            - COMPLETED
        statusDescription:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CustomerRequest:
      required:
        - cpf
        - email
        - name
      type: object
      properties:
        name:
          maxLength: 55
          minLength: 4
          type: string
        cpf:
          type: string
        email:
          type: string
    Customer:
      type: object
      properties:
        id:
          type: string
        document:
          $ref: '#/components/schemas/Document'
        name:
          type: string
        email:
          type: string
    Document:
      type: object
      properties:
        type:
          type: string
          enum:
            - CPF
        number:
          type: string
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          type: string
          enum:
            - LANCHE
            - ACOMPANHAMENTO
            - BEBIDA
            - SOBREMESA
        price:
          type: number
        description:
          type: string
        image:
          type: string
