version: '3.9'

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: fiap123
      POSTGRES_USER: fiap
      POSTGRES_DB: fiap
    ports:
      - 5432:5432
    volumes:
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql