version: '3.9'

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/fiap123
      - DATABASE_USER=fiap
      - DATABASE_PASSWORD=fiap
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: fiap123
      POSTGRES_USER: fiap
      POSTGRES_DB: fiap
    ports:
      - 5432:5432
    volumes:
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
