INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'Hamburguer', 'Pão, hamburguer de carne', 2.99, 'hamburguer.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'Cheeseburger', 'Pão, hamburguer de carne e queijo', 3.79, 'cheeseburger.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'X Burguer', 'Pão, hamburguer de carne, queijo, alface e tomate', 4.49, 'x-burguer.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'X Burguer Bacon', 'Pão, hamburguer de carne, queijo, bacon, alface e tomate', 5.74, 'x-burguer-bacon.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'X Tudo', 'Pão, hamburguer de carne, queijo, bacon, ovo, alface e tomate', 6.25, 'x-tudo.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(1, 'X Tudo Duplo', 'Pão, 2 hamburguers de carne, queijo, bacon, ovo, alface e tomate', 6.75, 'x-tudo-duplo.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(2, 'Batata pequena', 'Batata frita pequena', 3.59, 'batata-pequena.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(2, 'Batata média', 'Batata frita média', 4.69, 'batata-media.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(2, 'Batata grande', 'Batata frita grande', 5.99, 'batata-grande.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(3, 'Refrigerante pequeno', 'Refrigerante 300ml', 2.99, 'refrigerante-pequeno.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(3, 'Refrigerante médio', 'Refrigerante 450ml', 2.99, 'refrigerante-medio.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(3, 'Refrigerante grande', 'Refrigerante 750ml', 2.99, 'refrigerante-grande.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(4, 'Sorvete pequeno', 'Sorvete 150ml', 6.99, 'sorvete-pequeno.png');
INSERT INTO public.products (category, "name", description, price, image) VALUES(4, 'Sorvete médio', 'Sorvete 250ml', 8.99, 'sorvete-medio.png');