name: pipeline.yml
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

        name: Package
        run: mvn package

  publish:
      runs-on: ubuntu-latest
      needs: build
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
            package: '.jar'
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-developer:
        runs-on: ubuntu-latest
        environment:
          name: developer
        needs: publish

        if: github.ref == 'refs/heads/developer'
        steps:
          - name: Deploy
            shell: bash
            run:
              echo "Deploy Developer"


  deploy-QA:
        runs-on: ubuntu-latest
        environment:
          name: QA
        needs: publish

        if: github.ref == 'refs/heads/QA'
        steps:
          - name: Deploy
            shell: bash
            run:
              echo "Deploy QA"

  deploy-Preprod:
          runs-on: ubuntu-latest
          environment:
            name: Preprod
          needs: publish

          if: github.ref == 'refs/heads/Preprod'
          steps:
            - name: Deploy
              shell: bash
              run:
                echo "Deploy Preprod"

  deploy-Release:
        runs-on: ubuntu-latest
        environment:
          name: Release
        needs: publish

        if: github.ref == 'refs/heads/Release'
        steps:
          - name: Deploy
            shell: bash
            run:
              echo "Deploy Release"
